//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

namespace SPEAR.Models.Schemas.RadSeeker
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://physics.nist.gov/N42/2011/N42")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://physics.nist.gov/N42/2011/N42", IsNullable = false)]
    public partial class Spectrum
    {

        private string liveTimeDurationField;

        private SpectrumChannelData[] channelDataField;

        private string idField;

        private string radDetectorInformationReferenceField;

        private string energyCalibrationReferenceField;

        private string radRawSpectrumReferencesField;

        /// <remarks/>
        public string LiveTimeDuration
        {
            get
            {
                return this.liveTimeDurationField;
            }
            set
            {
                this.liveTimeDurationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChannelData", IsNullable = true)]
        public SpectrumChannelData[] ChannelData
        {
            get
            {
                return this.channelDataField;
            }
            set
            {
                this.channelDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string radDetectorInformationReference
        {
            get
            {
                return this.radDetectorInformationReferenceField;
            }
            set
            {
                this.radDetectorInformationReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string energyCalibrationReference
        {
            get
            {
                return this.energyCalibrationReferenceField;
            }
            set
            {
                this.energyCalibrationReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string radRawSpectrumReferences
        {
            get
            {
                return this.radRawSpectrumReferencesField;
            }
            set
            {
                this.radRawSpectrumReferencesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://physics.nist.gov/N42/2011/N42")]
    public partial class SpectrumChannelData
    {

        private string compressionCodeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string compressionCode
        {
            get
            {
                return this.compressionCodeField;
            }
            set
            {
                this.compressionCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://physics.nist.gov/N42/2011/N42")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://physics.nist.gov/N42/2011/N42", IsNullable = false)]
    public partial class RadInstrumentData
    {

        private RadInstrumentInformation[] radInstrumentInformationField;

        private RadInstrumentDataRadDetectorInformation[] radDetectorInformationField;

        private RadInstrumentDataEnergyCalibration[] energyCalibrationField;

        private RadMeasurement[] radMeasurementField;

        private RadInstrumentDataDerivedData[] derivedDataField;

        private AnalysisResults[] analysisResultsField;

        private string n42DocUUIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RadInstrumentInformation")]
        public RadInstrumentInformation[] RadInstrumentInformation
        {
            get
            {
                return this.radInstrumentInformationField;
            }
            set
            {
                this.radInstrumentInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RadDetectorInformation")]
        public RadInstrumentDataRadDetectorInformation[] RadDetectorInformation
        {
            get
            {
                return this.radDetectorInformationField;
            }
            set
            {
                this.radDetectorInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EnergyCalibration")]
        public RadInstrumentDataEnergyCalibration[] EnergyCalibration
        {
            get
            {
                return this.energyCalibrationField;
            }
            set
            {
                this.energyCalibrationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RadMeasurement")]
        public RadMeasurement[] RadMeasurement
        {
            get
            {
                return this.radMeasurementField;
            }
            set
            {
                this.radMeasurementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DerivedData")]
        public RadInstrumentDataDerivedData[] DerivedData
        {
            get
            {
                return this.derivedDataField;
            }
            set
            {
                this.derivedDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnalysisResults")]
        public AnalysisResults[] AnalysisResults
        {
            get
            {
                return this.analysisResultsField;
            }
            set
            {
                this.analysisResultsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string n42DocUUID
        {
            get
            {
                return this.n42DocUUIDField;
            }
            set
            {
                this.n42DocUUIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://physics.nist.gov/N42/2011/N42")]
    public partial class RadInstrumentInformation
    {

        private string radInstrumentManufacturerNameField;

        private string radInstrumentIdentifierField;

        private string radInstrumentModelNameField;

        private string radInstrumentClassCodeField;

        private RadInstrumentDataRadInstrumentInformationRadInstrumentVersion[] radInstrumentVersionField;

        private RadInstrumentDataRadInstrumentInformationRadInstrumentQualityControl[] radInstrumentQualityControlField;

        private string idField;

        /// <remarks/>
        public string RadInstrumentManufacturerName
        {
            get
            {
                return this.radInstrumentManufacturerNameField;
            }
            set
            {
                this.radInstrumentManufacturerNameField = value;
            }
        }

        /// <remarks/>
        public string RadInstrumentIdentifier
        {
            get
            {
                return this.radInstrumentIdentifierField;
            }
            set
            {
                this.radInstrumentIdentifierField = value;
            }
        }

        /// <remarks/>
        public string RadInstrumentModelName
        {
            get
            {
                return this.radInstrumentModelNameField;
            }
            set
            {
                this.radInstrumentModelNameField = value;
            }
        }

        /// <remarks/>
        public string RadInstrumentClassCode
        {
            get
            {
                return this.radInstrumentClassCodeField;
            }
            set
            {
                this.radInstrumentClassCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RadInstrumentVersion")]
        public RadInstrumentDataRadInstrumentInformationRadInstrumentVersion[] RadInstrumentVersion
        {
            get
            {
                return this.radInstrumentVersionField;
            }
            set
            {
                this.radInstrumentVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RadInstrumentQualityControl")]
        public RadInstrumentDataRadInstrumentInformationRadInstrumentQualityControl[] RadInstrumentQualityControl
        {
            get
            {
                return this.radInstrumentQualityControlField;
            }
            set
            {
                this.radInstrumentQualityControlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://physics.nist.gov/N42/2011/N42")]
    public partial class RadInstrumentDataRadInstrumentInformationRadInstrumentVersion
    {

        private string radInstrumentComponentNameField;

        private string radInstrumentComponentVersionField;

        /// <remarks/>
        public string RadInstrumentComponentName
        {
            get
            {
                return this.radInstrumentComponentNameField;
            }
            set
            {
                this.radInstrumentComponentNameField = value;
            }
        }

        /// <remarks/>
        public string RadInstrumentComponentVersion
        {
            get
            {
                return this.radInstrumentComponentVersionField;
            }
            set
            {
                this.radInstrumentComponentVersionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://physics.nist.gov/N42/2011/N42")]
    public partial class RadInstrumentDataRadInstrumentInformationRadInstrumentQualityControl
    {

        private string inspectionDateTimeField;

        private string inCalibrationIndicatorField;

        /// <remarks/>
        public string InspectionDateTime
        {
            get
            {
                return this.inspectionDateTimeField;
            }
            set
            {
                this.inspectionDateTimeField = value;
            }
        }

        /// <remarks/>
        public string InCalibrationIndicator
        {
            get
            {
                return this.inCalibrationIndicatorField;
            }
            set
            {
                this.inCalibrationIndicatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://physics.nist.gov/N42/2011/N42")]
    public partial class RadInstrumentDataRadDetectorInformation
    {

        private string radDetectorCategoryCodeField;

        private string radDetectorKindCodeField;

        private string radDetectorDescriptionField;

        private string radDetectorLengthValueField;

        private string radDetectorDiameterValueField;

        private string radDetectorVolumeValueField;

        private RadInstrumentDataRadDetectorInformationRadDetectorCharacteristicsCharacteristic[] radDetectorCharacteristicsField;

        private string idField;

        /// <remarks/>
        public string RadDetectorCategoryCode
        {
            get
            {
                return this.radDetectorCategoryCodeField;
            }
            set
            {
                this.radDetectorCategoryCodeField = value;
            }
        }

        /// <remarks/>
        public string RadDetectorKindCode
        {
            get
            {
                return this.radDetectorKindCodeField;
            }
            set
            {
                this.radDetectorKindCodeField = value;
            }
        }

        /// <remarks/>
        public string RadDetectorDescription
        {
            get
            {
                return this.radDetectorDescriptionField;
            }
            set
            {
                this.radDetectorDescriptionField = value;
            }
        }

        /// <remarks/>
        public string RadDetectorLengthValue
        {
            get
            {
                return this.radDetectorLengthValueField;
            }
            set
            {
                this.radDetectorLengthValueField = value;
            }
        }

        /// <remarks/>
        public string RadDetectorDiameterValue
        {
            get
            {
                return this.radDetectorDiameterValueField;
            }
            set
            {
                this.radDetectorDiameterValueField = value;
            }
        }

        /// <remarks/>
        public string RadDetectorVolumeValue
        {
            get
            {
                return this.radDetectorVolumeValueField;
            }
            set
            {
                this.radDetectorVolumeValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Characteristic", typeof(RadInstrumentDataRadDetectorInformationRadDetectorCharacteristicsCharacteristic), IsNullable = false)]
        public RadInstrumentDataRadDetectorInformationRadDetectorCharacteristicsCharacteristic[] RadDetectorCharacteristics
        {
            get
            {
                return this.radDetectorCharacteristicsField;
            }
            set
            {
                this.radDetectorCharacteristicsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://physics.nist.gov/N42/2011/N42")]
    public partial class RadInstrumentDataRadDetectorInformationRadDetectorCharacteristicsCharacteristic
    {

        private string characteristicNameField;

        private string characteristicValueField;

        private string characteristicValueUnitsField;

        private string characteristicValueDataClassCodeField;

        /// <remarks/>
        public string CharacteristicName
        {
            get
            {
                return this.characteristicNameField;
            }
            set
            {
                this.characteristicNameField = value;
            }
        }

        /// <remarks/>
        public string CharacteristicValue
        {
            get
            {
                return this.characteristicValueField;
            }
            set
            {
                this.characteristicValueField = value;
            }
        }

        /// <remarks/>
        public string CharacteristicValueUnits
        {
            get
            {
                return this.characteristicValueUnitsField;
            }
            set
            {
                this.characteristicValueUnitsField = value;
            }
        }

        /// <remarks/>
        public string CharacteristicValueDataClassCode
        {
            get
            {
                return this.characteristicValueDataClassCodeField;
            }
            set
            {
                this.characteristicValueDataClassCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://physics.nist.gov/N42/2011/N42")]
    public partial class RadInstrumentDataEnergyCalibration
    {

        private string coefficientValuesField;

        private string energyValuesField;

        private string energyDeviationValuesField;

        private string idField;

        /// <remarks/>
        public string CoefficientValues
        {
            get
            {
                return this.coefficientValuesField;
            }
            set
            {
                this.coefficientValuesField = value;
            }
        }

        /// <remarks/>
        public string EnergyValues
        {
            get
            {
                return this.energyValuesField;
            }
            set
            {
                this.energyValuesField = value;
            }
        }

        /// <remarks/>
        public string EnergyDeviationValues
        {
            get
            {
                return this.energyDeviationValuesField;
            }
            set
            {
                this.energyDeviationValuesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://physics.nist.gov/N42/2011/N42")]
    public partial class RadMeasurement
    {

        private string measurementClassCodeField;

        private string startDateTimeField;

        private string realTimeDurationField;

        private Spectrum[] spectrumField;

        private RadInstrumentDataRadMeasurementGrossCounts[] grossCountsField;

        private RadInstrumentDataRadMeasurementDoseRate[] doseRateField;

        private RadInstrumentDataRadMeasurementRadInstrumentState[] radInstrumentStateField;

        private string idField;

        /// <remarks/>
        public string MeasurementClassCode
        {
            get
            {
                return this.measurementClassCodeField;
            }
            set
            {
                this.measurementClassCodeField = value;
            }
        }

        /// <remarks/>
        public string StartDateTime
        {
            get
            {
                return this.startDateTimeField;
            }
            set
            {
                this.startDateTimeField = value;
            }
        }

        /// <remarks/>
        public string RealTimeDuration
        {
            get
            {
                return this.realTimeDurationField;
            }
            set
            {
                this.realTimeDurationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Spectrum")]
        public Spectrum[] Spectrum
        {
            get
            {
                return this.spectrumField;
            }
            set
            {
                this.spectrumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GrossCounts")]
        public RadInstrumentDataRadMeasurementGrossCounts[] GrossCounts
        {
            get
            {
                return this.grossCountsField;
            }
            set
            {
                this.grossCountsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DoseRate")]
        public RadInstrumentDataRadMeasurementDoseRate[] DoseRate
        {
            get
            {
                return this.doseRateField;
            }
            set
            {
                this.doseRateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RadInstrumentState")]
        public RadInstrumentDataRadMeasurementRadInstrumentState[] RadInstrumentState
        {
            get
            {
                return this.radInstrumentStateField;
            }
            set
            {
                this.radInstrumentStateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://physics.nist.gov/N42/2011/N42")]
    public partial class RadInstrumentDataRadMeasurementGrossCounts
    {

        private string liveTimeDurationField;

        private string countDataField;

        private string idField;

        private string radDetectorInformationReferenceField;

        /// <remarks/>
        public string LiveTimeDuration
        {
            get
            {
                return this.liveTimeDurationField;
            }
            set
            {
                this.liveTimeDurationField = value;
            }
        }

        /// <remarks/>
        public string CountData
        {
            get
            {
                return this.countDataField;
            }
            set
            {
                this.countDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string radDetectorInformationReference
        {
            get
            {
                return this.radDetectorInformationReferenceField;
            }
            set
            {
                this.radDetectorInformationReferenceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://physics.nist.gov/N42/2011/N42")]
    public partial class RadInstrumentDataRadMeasurementDoseRate
    {

        private string doseRateValueField;

        private string idField;

        private string radDetectorInformationReferenceField;

        /// <remarks/>
        public string DoseRateValue
        {
            get
            {
                return this.doseRateValueField;
            }
            set
            {
                this.doseRateValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string radDetectorInformationReference
        {
            get
            {
                return this.radDetectorInformationReferenceField;
            }
            set
            {
                this.radDetectorInformationReferenceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://physics.nist.gov/N42/2011/N42")]
    public partial class RadInstrumentDataRadMeasurementRadInstrumentState
    {

        private string radInstrumentModeCodeField;

        private string stateVectorField;

        private string radInstrumentInformationReferenceField;

        /// <remarks/>
        public string RadInstrumentModeCode
        {
            get
            {
                return this.radInstrumentModeCodeField;
            }
            set
            {
                this.radInstrumentModeCodeField = value;
            }
        }

        /// <remarks/>
        public string StateVector
        {
            get
            {
                return this.stateVectorField;
            }
            set
            {
                this.stateVectorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string radInstrumentInformationReference
        {
            get
            {
                return this.radInstrumentInformationReferenceField;
            }
            set
            {
                this.radInstrumentInformationReferenceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://physics.nist.gov/N42/2011/N42")]
    public partial class RadInstrumentDataDerivedData
    {

        private string measurementClassCodeField;

        private string startDateTimeField;

        private string realTimeDurationField;

        private Spectrum[] spectrumField;

        private string idField;

        /// <remarks/>
        public string MeasurementClassCode
        {
            get
            {
                return this.measurementClassCodeField;
            }
            set
            {
                this.measurementClassCodeField = value;
            }
        }

        /// <remarks/>
        public string StartDateTime
        {
            get
            {
                return this.startDateTimeField;
            }
            set
            {
                this.startDateTimeField = value;
            }
        }

        /// <remarks/>
        public string RealTimeDuration
        {
            get
            {
                return this.realTimeDurationField;
            }
            set
            {
                this.realTimeDurationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Spectrum")]
        public Spectrum[] Spectrum
        {
            get
            {
                return this.spectrumField;
            }
            set
            {
                this.spectrumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://physics.nist.gov/N42/2011/N42")]
    public partial class AnalysisResults
    {

        private string analysisAlgorithmNameField;

        private string analysisAlgorithmCreatorNameField;

        private RadInstrumentDataAnalysisResultsAnalysisAlgorithmVersion[] analysisAlgorithmVersionField;

        private RadInstrumentDataAnalysisResultsRadAlarm[] radAlarmField;

        private NuclideAnalysisResultsNuclide[] nuclideAnalysisResultsField;

        private RadInstrumentDataAnalysisResultsSpectrumPeakAnalysisResultsSpectrumPeak[] spectrumPeakAnalysisResultsField;

        private GrossCountAnalysisResults[] grossCountAnalysisResultsField;

        private string idField;

        private string derivedDataReferencesField;

        /// <remarks/>
        public string AnalysisAlgorithmName
        {
            get
            {
                return this.analysisAlgorithmNameField;
            }
            set
            {
                this.analysisAlgorithmNameField = value;
            }
        }

        /// <remarks/>
        public string AnalysisAlgorithmCreatorName
        {
            get
            {
                return this.analysisAlgorithmCreatorNameField;
            }
            set
            {
                this.analysisAlgorithmCreatorNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnalysisAlgorithmVersion")]
        public RadInstrumentDataAnalysisResultsAnalysisAlgorithmVersion[] AnalysisAlgorithmVersion
        {
            get
            {
                return this.analysisAlgorithmVersionField;
            }
            set
            {
                this.analysisAlgorithmVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RadAlarm")]
        public RadInstrumentDataAnalysisResultsRadAlarm[] RadAlarm
        {
            get
            {
                return this.radAlarmField;
            }
            set
            {
                this.radAlarmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Nuclide", typeof(NuclideAnalysisResultsNuclide), IsNullable = false)]
        public NuclideAnalysisResultsNuclide[] NuclideAnalysisResults
        {
            get
            {
                return this.nuclideAnalysisResultsField;
            }
            set
            {
                this.nuclideAnalysisResultsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SpectrumPeak", typeof(RadInstrumentDataAnalysisResultsSpectrumPeakAnalysisResultsSpectrumPeak), IsNullable = false)]
        public RadInstrumentDataAnalysisResultsSpectrumPeakAnalysisResultsSpectrumPeak[] SpectrumPeakAnalysisResults
        {
            get
            {
                return this.spectrumPeakAnalysisResultsField;
            }
            set
            {
                this.spectrumPeakAnalysisResultsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GrossCountAnalysisResults")]
        public GrossCountAnalysisResults[] GrossCountAnalysisResults
        {
            get
            {
                return this.grossCountAnalysisResultsField;
            }
            set
            {
                this.grossCountAnalysisResultsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string derivedDataReferences
        {
            get
            {
                return this.derivedDataReferencesField;
            }
            set
            {
                this.derivedDataReferencesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://physics.nist.gov/N42/2011/N42")]
    public partial class RadInstrumentDataAnalysisResultsAnalysisAlgorithmVersion
    {

        private string analysisAlgorithmComponentNameField;

        private string analysisAlgorithmComponentVersionField;

        /// <remarks/>
        public string AnalysisAlgorithmComponentName
        {
            get
            {
                return this.analysisAlgorithmComponentNameField;
            }
            set
            {
                this.analysisAlgorithmComponentNameField = value;
            }
        }

        /// <remarks/>
        public string AnalysisAlgorithmComponentVersion
        {
            get
            {
                return this.analysisAlgorithmComponentVersionField;
            }
            set
            {
                this.analysisAlgorithmComponentVersionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://physics.nist.gov/N42/2011/N42")]
    public partial class RadInstrumentDataAnalysisResultsRadAlarm
    {

        private string radAlarmDateTimeField;

        private string radAlarmCategoryCodeField;

        private string radAlarmDescriptionField;

        private string radAlarmLightColorField;

        private string idField;

        private string radDetectorInformationReferencesField;

        /// <remarks/>
        public string RadAlarmDateTime
        {
            get
            {
                return this.radAlarmDateTimeField;
            }
            set
            {
                this.radAlarmDateTimeField = value;
            }
        }

        /// <remarks/>
        public string RadAlarmCategoryCode
        {
            get
            {
                return this.radAlarmCategoryCodeField;
            }
            set
            {
                this.radAlarmCategoryCodeField = value;
            }
        }

        /// <remarks/>
        public string RadAlarmDescription
        {
            get
            {
                return this.radAlarmDescriptionField;
            }
            set
            {
                this.radAlarmDescriptionField = value;
            }
        }

        /// <remarks/>
        public string RadAlarmLightColor
        {
            get
            {
                return this.radAlarmLightColorField;
            }
            set
            {
                this.radAlarmLightColorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string radDetectorInformationReferences
        {
            get
            {
                return this.radDetectorInformationReferencesField;
            }
            set
            {
                this.radDetectorInformationReferencesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://physics.nist.gov/N42/2011/N42")]
    public partial class NuclideAnalysisResultsNuclide
    {

        private string nuclideIdentifiedIndicatorField;

        private string nuclideNameField;

        private string nuclideIDConfidenceValueField;

        private string nuclideCategoryDescriptionField;

        /// <remarks/>
        public string NuclideIdentifiedIndicator
        {
            get
            {
                return this.nuclideIdentifiedIndicatorField;
            }
            set
            {
                this.nuclideIdentifiedIndicatorField = value;
            }
        }

        /// <remarks/>
        public string NuclideName
        {
            get
            {
                return this.nuclideNameField;
            }
            set
            {
                this.nuclideNameField = value;
            }
        }

        /// <remarks/>
        public string NuclideIDConfidenceValue
        {
            get
            {
                return this.nuclideIDConfidenceValueField;
            }
            set
            {
                this.nuclideIDConfidenceValueField = value;
            }
        }

        /// <remarks/>
        public string NuclideCategoryDescription
        {
            get
            {
                return this.nuclideCategoryDescriptionField;
            }
            set
            {
                this.nuclideCategoryDescriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://physics.nist.gov/N42/2011/N42")]
    public partial class RadInstrumentDataAnalysisResultsSpectrumPeakAnalysisResultsSpectrumPeak
    {

        private string spectrumPeakEnergyValueField;

        private string spectrumPeakExpectedEnergyValueField;

        private string spectrumPeakNetAreaValueField;

        /// <remarks/>
        public string SpectrumPeakEnergyValue
        {
            get
            {
                return this.spectrumPeakEnergyValueField;
            }
            set
            {
                this.spectrumPeakEnergyValueField = value;
            }
        }

        /// <remarks/>
        public string SpectrumPeakExpectedEnergyValue
        {
            get
            {
                return this.spectrumPeakExpectedEnergyValueField;
            }
            set
            {
                this.spectrumPeakExpectedEnergyValueField = value;
            }
        }

        /// <remarks/>
        public string SpectrumPeakNetAreaValue
        {
            get
            {
                return this.spectrumPeakNetAreaValueField;
            }
            set
            {
                this.spectrumPeakNetAreaValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://physics.nist.gov/N42/2011/N42")]
    public partial class GrossCountAnalysisResults
    {

        private string averageCountRateValueField;

        private string backgroundCountRateValueField;

        /// <remarks/>
        public string AverageCountRateValue
        {
            get
            {
                return this.averageCountRateValueField;
            }
            set
            {
                this.averageCountRateValueField = value;
            }
        }

        /// <remarks/>
        public string BackgroundCountRateValue
        {
            get
            {
                return this.backgroundCountRateValueField;
            }
            set
            {
                this.backgroundCountRateValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://physics.nist.gov/N42/2011/N42")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://physics.nist.gov/N42/2011/N42", IsNullable = false)]
    public partial class NewDataSet
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RadInstrumentData", typeof(RadInstrumentData))]
        [System.Xml.Serialization.XmlElementAttribute("Spectrum", typeof(Spectrum))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
}
