using System;
using System.Xml;
using System.Xml.Serialization;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.ComponentModel;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
//

namespace SPEAR.Models.N42.v2006
{
    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    //[XmlTypeAttribute(Namespace="http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    //[XmlRootAttribute(Namespace="http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242", IsNullable = false)]
    public partial class N42InstrumentData {

        private string remarkField;

        private Measurement[] measurementField;

        private Calibration[] calibrationField;

        private XmlElement[] anyField;

        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("Measurement")]
        public Measurement[] Measurement {
            get {
                return this.measurementField;
            }
            set {
                this.measurementField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("Calibration")]
        public Calibration[] Calibration {
            get {
                return this.calibrationField;
            }
            set {
                this.calibrationField = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class Measurement {

        private string remarkField;

        private InstrumentInformation instrumentInformationField;

        private MeasuredItemInformation measuredItemInformationField;

        private Spectrum[] spectrumField;

        private DetectorData[] detectorDataField;

        private CountDoseData[] countDoseDataField;

        private AnalysisResults[] analysisResultsField;

        private XmlElement[] anyField;

        private string uUIDField;

        private XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        public InstrumentInformation InstrumentInformation {
            get {
                return this.instrumentInformationField;
            }
            set {
                this.instrumentInformationField = value;
            }
        }

        /// <remarks/>
        public MeasuredItemInformation MeasuredItemInformation {
            get {
                return this.measuredItemInformationField;
            }
            set {
                this.measuredItemInformationField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("Spectrum")]
        public Spectrum[] Spectrum {
            get {
                return this.spectrumField;
            }
            set {
                this.spectrumField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("DetectorData")]
        public DetectorData[] DetectorData {
            get {
                return this.detectorDataField;
            }
            set {
                this.detectorDataField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("CountDoseData")]
        public CountDoseData[] CountDoseData {
            get {
                return this.countDoseDataField;
            }
            set {
                this.countDoseDataField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("AnalysisResults")]
        public AnalysisResults[] AnalysisResults {
            get {
                return this.analysisResultsField;
            }
            set {
                this.analysisResultsField = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class InstrumentInformation {

        private string remarkField;

        private enumInstrumentType instrumentTypeField;

        private bool instrumentTypeFieldSpecified;

        private string manufacturerField;

        private string instrumentModelField;

        private string instrumentVersionField;

        private string instrumentIDField;

        private string probeTypeField;

        private enumInstrumentMode instrumentModeField;

        private bool instrumentModeFieldSpecified;

        private QualityControl qualityControlField;

        private XmlElement[] anyField;

        private XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        public enumInstrumentType InstrumentType {
            get {
                return this.instrumentTypeField;
            }
            set {
                this.instrumentTypeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool InstrumentTypeSpecified {
            get {
                return this.instrumentTypeFieldSpecified;
            }
            set {
                this.instrumentTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
            }
        }

        /// <remarks/>
        public string InstrumentModel {
            get {
                return this.instrumentModelField;
            }
            set {
                this.instrumentModelField = value;
            }
        }

        /// <remarks/>
        public string InstrumentVersion {
            get {
                return this.instrumentVersionField;
            }
            set {
                this.instrumentVersionField = value;
            }
        }

        /// <remarks/>
        public string InstrumentID {
            get {
                return this.instrumentIDField;
            }
            set {
                this.instrumentIDField = value;
            }
        }

        /// <remarks/>
        public string ProbeType {
            get {
                return this.probeTypeField;
            }
            set {
                this.probeTypeField = value;
            }
        }

        /// <remarks/>
        public enumInstrumentMode InstrumentMode {
            get {
                return this.instrumentModeField;
            }
            set {
                this.instrumentModeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool InstrumentModeSpecified {
            get {
                return this.instrumentModeFieldSpecified;
            }
            set {
                this.instrumentModeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public QualityControl QualityControl {
            get {
                return this.qualityControlField;
            }
            set {
                this.qualityControlField = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public enum enumInstrumentType {

        /// <remarks/>
        PortalMonitor,

        /// <remarks/>
        SpecPortal,

        /// <remarks/>
        RadionuclideIdentifier,

        /// <remarks/>
        PersonalRadiationDetector,

        /// <remarks/>
        SurveyMeter,

        /// <remarks/>
        Spectrometer,

        /// <remarks/>
        Other,
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public enum enumInstrumentMode {

        /// <remarks/>
        Measure,

        /// <remarks/>
        Calibrate,

        /// <remarks/>
        Test,

        /// <remarks/>
        Other,
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class QualityControl {

        private string remarkField;

        private DateTime inspectionDateField;

        private bool inspectionDateFieldSpecified;

        private bool inServiceField;

        private bool inServiceFieldSpecified;

        private XmlElement[] anyField;

        private XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        public DateTime InspectionDate {
            get {
                return this.inspectionDateField;
            }
            set {
                this.inspectionDateField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool InspectionDateSpecified {
            get {
                return this.inspectionDateFieldSpecified;
            }
            set {
                this.inspectionDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool InService {
            get {
                return this.inServiceField;
            }
            set {
                this.inServiceField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool InServiceSpecified {
            get {
                return this.inServiceFieldSpecified;
            }
            set {
                this.inServiceFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class Nuclide {

        private string remarkField;

        private string nuclideNameField;

        private string nuclideTypeField;

        private string nuclideActivityField;

        private double nuclideIDConfidenceIndicationField;

        private bool nuclideIDConfidenceIndicationFieldSpecified;

        private string nuclideIDConfidenceDescriptionField;

        private XmlElement[] anyField;

        private XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        public string NuclideName {
            get {
                return this.nuclideNameField;
            }
            set {
                this.nuclideNameField = value;
            }
        }

        /// <remarks/>
        public string NuclideType {
            get {
                return this.nuclideTypeField;
            }
            set {
                this.nuclideTypeField = value;
            }
        }

        /// <remarks/>
        public string NuclideActivity {
            get {
                return this.nuclideActivityField;
            }
            set {
                this.nuclideActivityField = value;
            }
        }

        /// <remarks/>
        public double NuclideIDConfidenceIndication {
            get {
                return this.nuclideIDConfidenceIndicationField;
            }
            set {
                this.nuclideIDConfidenceIndicationField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool NuclideIDConfidenceIndicationSpecified {
            get {
                return this.nuclideIDConfidenceIndicationFieldSpecified;
            }
            set {
                this.nuclideIDConfidenceIndicationFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string NuclideIDConfidenceDescription {
            get {
                return this.nuclideIDConfidenceDescriptionField;
            }
            set {
                this.nuclideIDConfidenceDescriptionField = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class NuclideAnalysis {

        private string remarkField;

        private Nuclide[] nuclideField;

        private XmlElement[] anyField;

        private enumActivityUnits activityUnitsField;

        private string algorithmDescriptionField;

        private string algorithmVersionField;

        private XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("Nuclide")]
        public Nuclide[] Nuclide {
            get {
                return this.nuclideField;
            }
            set {
                this.nuclideField = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumActivityUnits ActivityUnits {
            get {
                return this.activityUnitsField;
            }
            set {
                this.activityUnitsField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string AlgorithmDescription {
            get {
                return this.algorithmDescriptionField;
            }
            set {
                this.algorithmDescriptionField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string AlgorithmVersion {
            get {
                return this.algorithmVersionField;
            }
            set {
                this.algorithmVersionField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public enum enumActivityUnits {

        /// <remarks/>
        mBq,

        /// <remarks/>
        Bq,

        /// <remarks/>
        kBq,

        /// <remarks/>
        MBq,

        /// <remarks/>
        nCi,

        /// <remarks/>
        uCi,

        /// <remarks/>
        mCi,

        /// <remarks/>
        Ci,

        /// <remarks/>
        kCi,

        /// <remarks/>
        MCi,
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class AnalysisResults {

        private string remarkField;

        private string threatDescriptionField;

        private NuclideAnalysis nuclideAnalysisField;

        private XmlElement[] anyField;

        private XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        public string ThreatDescription {
            get {
                return this.threatDescriptionField;
            }
            set {
                this.threatDescriptionField = value;
            }
        }

        /// <remarks/>
        public NuclideAnalysis NuclideAnalysis {
            get {
                return this.nuclideAnalysisField;
            }
            set {
                this.nuclideAnalysisField = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class Exposure {

        private enumExposureUnits unitsField;

        private XmlAttribute[] anyAttrField;

        private string textField;

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumExposureUnits Units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }

        /// <remarks/>
        [XmlTextAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public enum enumExposureUnits {

        /// <remarks/>
        [XmlEnumAttribute("C/kg")]
        Ckg,

        /// <remarks/>
        uR,

        /// <remarks/>
        mR,

        /// <remarks/>
        R,
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class AbsorbedDose {

        private enumAbsorbedDoseUnits unitsField;

        private XmlAttribute[] anyAttrField;

        private string textField;

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumAbsorbedDoseUnits Units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }

        /// <remarks/>
        [XmlTextAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public enum enumAbsorbedDoseUnits {

        /// <remarks/>
        uGy,

        /// <remarks/>
        mGy,

        /// <remarks/>
        Gy,

        /// <remarks/>
        rad,
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class Dose {

        private enumDoseUnits unitsField;

        private XmlAttribute[] anyAttrField;

        private string textField;

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumDoseUnits Units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }

        /// <remarks/>
        [XmlTextAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public enum enumDoseUnits {

        /// <remarks/>
        urem,

        /// <remarks/>
        mrem,

        /// <remarks/>
        rem,

        /// <remarks/>
        uSv,

        /// <remarks/>
        mSv,

        /// <remarks/>
        Sv,
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class Count {

        private enumCountRateUnits unitsField;

        private XmlAttribute[] anyAttrField;

        private string textField;

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumCountRateUnits Units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }

        /// <remarks/>
        [XmlTextAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public enum enumCountRateUnits {

        /// <remarks/>
        CPS,

        /// <remarks/>
        CPM,
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class CountDoseData {

        private string remarkField;

        private DateTime startTimeField;

        private bool startTimeFieldSpecified;

        private string sampleRealTimeField;

        private string sampleLiveTimeField;

        private string alarmedField;

        private bool alarmSummaryField;

        private bool alarmSummaryFieldSpecified;

        private string[] alarmDescriptionField;

        private Calibration[] calibrationField;

        private Count countRateField;

        private string countsField;

        private Dose doseRateField;

        private Dose totalDoseField;

        private AbsorbedDose absorbedDoseRateField;

        private AbsorbedDose totalAbsorbedDoseField;

        private Exposure exposureRateField;

        private Exposure totalExposureField;

        private XmlElement[] anyField;

        private string calibrationIDsField;

        private string detectorField;

        private enumGrossCountDetectorType detectorTypeField;

        private bool detectorTypeFieldSpecified;

        private enumQualityStatus qualityField;

        private bool qualityFieldSpecified;

        private XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        public DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool StartTimeSpecified {
            get {
                return this.startTimeFieldSpecified;
            }
            set {
                this.startTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(DataType = "duration")]
        public string SampleRealTime {
            get {
                return this.sampleRealTimeField;
            }
            set {
                this.sampleRealTimeField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(DataType = "duration")]
        public string SampleLiveTime {
            get {
                return this.sampleLiveTimeField;
            }
            set {
                this.sampleLiveTimeField = value;
            }
        }

        /// <remarks/>
        public string Alarmed {
            get {
                return this.alarmedField;
            }
            set {
                this.alarmedField = value;
            }
        }

        /// <remarks/>
        public bool AlarmSummary {
            get {
                return this.alarmSummaryField;
            }
            set {
                this.alarmSummaryField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool AlarmSummarySpecified {
            get {
                return this.alarmSummaryFieldSpecified;
            }
            set {
                this.alarmSummaryFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("AlarmDescription")]
        public string[] AlarmDescription {
            get {
                return this.alarmDescriptionField;
            }
            set {
                this.alarmDescriptionField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("Calibration")]
        public Calibration[] Calibration {
            get {
                return this.calibrationField;
            }
            set {
                this.calibrationField = value;
            }
        }

        /// <remarks/>
        public Count CountRate {
            get {
                return this.countRateField;
            }
            set {
                this.countRateField = value;
            }
        }

        /// <remarks/>
        public string Counts {
            get {
                return this.countsField;
            }
            set {
                this.countsField = value;
            }
        }

        /// <remarks/>
        public Dose DoseRate {
            get {
                return this.doseRateField;
            }
            set {
                this.doseRateField = value;
            }
        }

        /// <remarks/>
        public Dose TotalDose {
            get {
                return this.totalDoseField;
            }
            set {
                this.totalDoseField = value;
            }
        }

        /// <remarks/>
        public AbsorbedDose AbsorbedDoseRate {
            get {
                return this.absorbedDoseRateField;
            }
            set {
                this.absorbedDoseRateField = value;
            }
        }

        /// <remarks/>
        public AbsorbedDose TotalAbsorbedDose {
            get {
                return this.totalAbsorbedDoseField;
            }
            set {
                this.totalAbsorbedDoseField = value;
            }
        }

        /// <remarks/>
        public Exposure ExposureRate {
            get {
                return this.exposureRateField;
            }
            set {
                this.exposureRateField = value;
            }
        }

        /// <remarks/>
        public Exposure TotalExposure {
            get {
                return this.totalExposureField;
            }
            set {
                this.totalExposureField = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "IDREFS")]
        public string CalibrationIDs {
            get {
                return this.calibrationIDsField;
            }
            set {
                this.calibrationIDsField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Detector {
            get {
                return this.detectorField;
            }
            set {
                this.detectorField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumGrossCountDetectorType DetectorType {
            get {
                return this.detectorTypeField;
            }
            set {
                this.detectorTypeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool DetectorTypeSpecified {
            get {
                return this.detectorTypeFieldSpecified;
            }
            set {
                this.detectorTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumQualityStatus Quality {
            get {
                return this.qualityField;
            }
            set {
                this.qualityField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool QualitySpecified {
            get {
                return this.qualityFieldSpecified;
            }
            set {
                this.qualityFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class Calibration {

        private string remarkField;

        private DateTime calibrationCreationDateField;

        private bool calibrationCreationDateFieldSpecified;

        private string[] calibrationMeasurementUUIDField;

        private Equation[] equationField;

        private ArrayXY arrayXYField;

        private XmlElement[] anyField;

        private enumCalibrationType typeField;

        private enumEnergyUnits energyUnitsField;

        private bool energyUnitsFieldSpecified;

        private enumFWHMUnits fWHMUnitsField;

        private bool fWHMUnitsFieldSpecified;

        private enumCountRateUnits countRateUnitsField;

        private bool countRateUnitsFieldSpecified;

        private enumDoseUnits doseUnitsField;

        private bool doseUnitsFieldSpecified;

        private enumAbsorbedDoseUnits absorbedDoseUnitsField;

        private bool absorbedDoseUnitsFieldSpecified;

        private enumExposureUnits exposureUnitsField;

        private bool exposureUnitsFieldSpecified;

        private string idField;

        private XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        public DateTime CalibrationCreationDate {
            get {
                return this.calibrationCreationDateField;
            }
            set {
                this.calibrationCreationDateField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool CalibrationCreationDateSpecified {
            get {
                return this.calibrationCreationDateFieldSpecified;
            }
            set {
                this.calibrationCreationDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("CalibrationMeasurementUUID")]
        public string[] CalibrationMeasurementUUID {
            get {
                return this.calibrationMeasurementUUIDField;
            }
            set {
                this.calibrationMeasurementUUIDField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("Equation")]
        public Equation[] Equation {
            get {
                return this.equationField;
            }
            set {
                this.equationField = value;
            }
        }

        /// <remarks/>
        public ArrayXY ArrayXY {
            get {
                return this.arrayXYField;
            }
            set {
                this.arrayXYField = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumCalibrationType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumEnergyUnits EnergyUnits {
            get {
                return this.energyUnitsField;
            }
            set {
                this.energyUnitsField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool EnergyUnitsSpecified {
            get {
                return this.energyUnitsFieldSpecified;
            }
            set {
                this.energyUnitsFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumFWHMUnits FWHMUnits {
            get {
                return this.fWHMUnitsField;
            }
            set {
                this.fWHMUnitsField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool FWHMUnitsSpecified {
            get {
                return this.fWHMUnitsFieldSpecified;
            }
            set {
                this.fWHMUnitsFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumCountRateUnits CountRateUnits {
            get {
                return this.countRateUnitsField;
            }
            set {
                this.countRateUnitsField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool CountRateUnitsSpecified {
            get {
                return this.countRateUnitsFieldSpecified;
            }
            set {
                this.countRateUnitsFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumDoseUnits DoseUnits {
            get {
                return this.doseUnitsField;
            }
            set {
                this.doseUnitsField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool DoseUnitsSpecified {
            get {
                return this.doseUnitsFieldSpecified;
            }
            set {
                this.doseUnitsFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumAbsorbedDoseUnits AbsorbedDoseUnits {
            get {
                return this.absorbedDoseUnitsField;
            }
            set {
                this.absorbedDoseUnitsField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool AbsorbedDoseUnitsSpecified {
            get {
                return this.absorbedDoseUnitsFieldSpecified;
            }
            set {
                this.absorbedDoseUnitsFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumExposureUnits ExposureUnits {
            get {
                return this.exposureUnitsField;
            }
            set {
                this.exposureUnitsField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool ExposureUnitsSpecified {
            get {
                return this.exposureUnitsFieldSpecified;
            }
            set {
                this.exposureUnitsFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class Equation {

        private string remarkField;

        private Coefficients[] coefficientsField;

        private string covarianceMatrixField;

        private XmlElement[] anyField;

        private enumEquationType modelField;

        private string formField;

        private double lowerLimitField;

        private bool lowerLimitFieldSpecified;

        private double upperLimitField;

        private bool upperLimitFieldSpecified;

        private XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("Coefficients")]
        public Coefficients[] Coefficients {
            get {
                return this.coefficientsField;
            }
            set {
                this.coefficientsField = value;
            }
        }

        /// <remarks/>
        public string CovarianceMatrix {
            get {
                return this.covarianceMatrixField;
            }
            set {
                this.covarianceMatrixField = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumEquationType Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Form {
            get {
                return this.formField;
            }
            set {
                this.formField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public double LowerLimit {
            get {
                return this.lowerLimitField;
            }
            set {
                this.lowerLimitField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool LowerLimitSpecified {
            get {
                return this.lowerLimitFieldSpecified;
            }
            set {
                this.lowerLimitFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public double UpperLimit {
            get {
                return this.upperLimitField;
            }
            set {
                this.upperLimitField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool UpperLimitSpecified {
            get {
                return this.upperLimitFieldSpecified;
            }
            set {
                this.upperLimitFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class Coefficients {

        private string subequationField;

        private XmlAttribute[] anyAttrField;

        private string textField;

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "positiveInteger")]
        public string Subequation {
            get {
                return this.subequationField;
            }
            set {
                this.subequationField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }

        /// <remarks/>
        [XmlTextAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public enum enumEquationType {

        /// <remarks/>
        Polynomial,

        /// <remarks/>
        Pade,

        /// <remarks/>
        Exponential,

        /// <remarks/>
        PolyLogarithmic,

        /// <remarks/>
        FullRangeFraction,

        /// <remarks/>
        Other,
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class ArrayXY {

        private string remarkField;

        private PointXY[] pointXYField;

        private XmlElement[] anyField;

        private string xField;

        private string yField;

        private XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("PointXY")]
        public PointXY[] PointXY {
            get {
                return this.pointXYField;
            }
            set {
                this.pointXYField = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class PointXY {

        private string remarkField;

        private string xField;

        private string yField;

        private XmlElement[] anyField;

        private XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        public string X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }

        /// <remarks/>
        public string Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public enum enumCalibrationType {

        /// <remarks/>
        Energy,

        /// <remarks/>
        AbsoluteEfficiency,

        /// <remarks/>
        IntrinsicFullEnergyPeakEfficiency,

        /// <remarks/>
        IntrinsicTotalEfficiency,

        /// <remarks/>
        FWHM,

        /// <remarks/>
        CountsToDose,

        /// <remarks/>
        CountsToAbsorbedDose,

        /// <remarks/>
        CountsToExposure,

        /// <remarks/>
        Other,
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public enum enumEnergyUnits {

        /// <remarks/>
        eV,

        /// <remarks/>
        keV,

        /// <remarks/>
        MeV,
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public enum enumFWHMUnits {

        /// <remarks/>
        Energy,

        /// <remarks/>
        Channels,
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public enum enumGrossCountDetectorType {

        /// <remarks/>
        Alpha,

        /// <remarks/>
        Beta,

        /// <remarks/>
        Gamma,

        /// <remarks/>
        Neutron,

        /// <remarks/>
        Other,
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public enum enumQualityStatus {

        /// <remarks/>
        Good,

        /// <remarks/>
        Bad,

        /// <remarks/>
        Suspect,

        /// <remarks/>
        Missing,
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class SpectrumMeasurement {

        private string remarkField;

        private string spectrumAvailableField;

        private string alarmedField;

        private Spectrum[] spectrumField;

        private XmlElement[] anyField;

        private XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        public string SpectrumAvailable {
            get {
                return this.spectrumAvailableField;
            }
            set {
                this.spectrumAvailableField = value;
            }
        }

        /// <remarks/>
        public string Alarmed {
            get {
                return this.alarmedField;
            }
            set {
                this.alarmedField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("Spectrum")]
        public Spectrum[] Spectrum {
            get {
                return this.spectrumField;
            }
            set {
                this.spectrumField = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class Spectrum {

        private string remarkField;

        private DateTime startTimeField;

        private bool startTimeFieldSpecified;

        private string realTimeField;

        private string liveTimeField;

        private string dwellDurationField;

        private string elapsedSweepsField;

        private enumSourceType sourceTypeField;

        private bool sourceTypeFieldSpecified;

        private string detectorTypeField;

        private Calibration[] calibrationField;

        private ChannelData[] channelDataField;

        private XmlElement[] anyField;

        private enumSpectrumType typeField;

        private bool typeFieldSpecified;

        private string detectorField;

        private enumQualityStatus qualityField;

        private bool qualityFieldSpecified;

        private string idField;

        private string calibrationIDsField;

        private string backgroundSpectrumIDField;

        private string calibrationSpectrumIDField;

        private string sampleNumberField;

        private XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        public DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool StartTimeSpecified {
            get {
                return this.startTimeFieldSpecified;
            }
            set {
                this.startTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(DataType = "duration")]
        public string RealTime {
            get {
                return this.realTimeField;
            }
            set {
                this.realTimeField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(DataType = "duration")]
        public string LiveTime {
            get {
                return this.liveTimeField;
            }
            set {
                this.liveTimeField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(DataType = "duration")]
        public string DwellDuration {
            get {
                return this.dwellDurationField;
            }
            set {
                this.dwellDurationField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string ElapsedSweeps {
            get {
                return this.elapsedSweepsField;
            }
            set {
                this.elapsedSweepsField = value;
            }
        }

        /// <remarks/>
        public enumSourceType SourceType {
            get {
                return this.sourceTypeField;
            }
            set {
                this.sourceTypeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool SourceTypeSpecified {
            get {
                return this.sourceTypeFieldSpecified;
            }
            set {
                this.sourceTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string DetectorType {
            get {
                return this.detectorTypeField;
            }
            set {
                this.detectorTypeField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("Calibration")]
        public Calibration[] Calibration {
            get {
                return this.calibrationField;
            }
            set {
                this.calibrationField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("ChannelData")]
        public ChannelData[] ChannelData {
            get {
                return this.channelDataField;
            }
            set {
                this.channelDataField = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumSpectrumType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Detector {
            get {
                return this.detectorField;
            }
            set {
                this.detectorField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumQualityStatus Quality {
            get {
                return this.qualityField;
            }
            set {
                this.qualityField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool QualitySpecified {
            get {
                return this.qualityFieldSpecified;
            }
            set {
                this.qualityFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "IDREFS")]
        public string CalibrationIDs {
            get {
                return this.calibrationIDsField;
            }
            set {
                this.calibrationIDsField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "IDREF")]
        public string BackgroundSpectrumID {
            get {
                return this.backgroundSpectrumIDField;
            }
            set {
                this.backgroundSpectrumIDField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "IDREF")]
        public string CalibrationSpectrumID {
            get {
                return this.calibrationSpectrumIDField;
            }
            set {
                this.calibrationSpectrumIDField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "positiveInteger")]
        public string SampleNumber {
            get {
                return this.sampleNumberField;
            }
            set {
                this.sampleNumberField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public enum enumSourceType {

        /// <remarks/>
        Item,

        /// <remarks/>
        Background,

        /// <remarks/>
        Calibration,

        /// <remarks/>
        Other,
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class ChannelData {

        private string startField;

        private enumSpectrumCompressionType compressionField;

        private bool compressionFieldSpecified;

        private XmlAttribute[] anyAttrField;

        private string textField;

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "positiveInteger")]
        public string Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumSpectrumCompressionType Compression {
            get {
                return this.compressionField;
            }
            set {
                this.compressionField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool CompressionSpecified {
            get {
                return this.compressionFieldSpecified;
            }
            set {
                this.compressionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }

        /// <remarks/>
        [XmlTextAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public enum enumSpectrumCompressionType {

        /// <remarks/>
        None,

        /// <remarks/>
        CountedZeroes,
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public enum enumSpectrumType {

        /// <remarks/>
        PHA,

        /// <remarks/>
        MCS,

        /// <remarks/>
        Other,
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class GrossCountMeasurement {

        private string remarkField;

        private string sampleLiveTimeField;

        private string alarmedField;

        private string grossCountsField;

        private string backgroundCountsField;

        private XmlElement[] anyField;

        private double windowStartField;

        private bool windowStartFieldSpecified;

        private double windowEndField;

        private bool windowEndFieldSpecified;

        private enumEnergyUnits energyUnitsField;

        private bool energyUnitsFieldSpecified;

        private enumQualityStatus qualityField;

        private bool qualityFieldSpecified;

        private XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(DataType = "duration")]
        public string SampleLiveTime {
            get {
                return this.sampleLiveTimeField;
            }
            set {
                this.sampleLiveTimeField = value;
            }
        }

        /// <remarks/>
        public string Alarmed {
            get {
                return this.alarmedField;
            }
            set {
                this.alarmedField = value;
            }
        }

        /// <remarks/>
        public string GrossCounts {
            get {
                return this.grossCountsField;
            }
            set {
                this.grossCountsField = value;
            }
        }

        /// <remarks/>
        public string BackgroundCounts {
            get {
                return this.backgroundCountsField;
            }
            set {
                this.backgroundCountsField = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public double WindowStart {
            get {
                return this.windowStartField;
            }
            set {
                this.windowStartField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool WindowStartSpecified {
            get {
                return this.windowStartFieldSpecified;
            }
            set {
                this.windowStartFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public double WindowEnd {
            get {
                return this.windowEndField;
            }
            set {
                this.windowEndField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool WindowEndSpecified {
            get {
                return this.windowEndFieldSpecified;
            }
            set {
                this.windowEndFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumEnergyUnits EnergyUnits {
            get {
                return this.energyUnitsField;
            }
            set {
                this.energyUnitsField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool EnergyUnitsSpecified {
            get {
                return this.energyUnitsFieldSpecified;
            }
            set {
                this.energyUnitsFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumQualityStatus Quality {
            get {
                return this.qualityField;
            }
            set {
                this.qualityField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool QualitySpecified {
            get {
                return this.qualityFieldSpecified;
            }
            set {
                this.qualityFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class DetectorMeasurement {

        private string remarkField;

        private GrossCountMeasurement[] grossCountMeasurementField;

        private SpectrumMeasurement spectrumMeasurementField;

        private XmlElement[] anyField;

        private string detectorField;

        private enumGrossCountDetectorType detectorTypeField;

        private XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("GrossCountMeasurement")]
        public GrossCountMeasurement[] GrossCountMeasurement {
            get {
                return this.grossCountMeasurementField;
            }
            set {
                this.grossCountMeasurementField = value;
            }
        }

        /// <remarks/>
        public SpectrumMeasurement SpectrumMeasurement {
            get {
                return this.spectrumMeasurementField;
            }
            set {
                this.spectrumMeasurementField = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Detector {
            get {
                return this.detectorField;
            }
            set {
                this.detectorField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumGrossCountDetectorType DetectorType {
            get {
                return this.detectorTypeField;
            }
            set {
                this.detectorTypeField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class Speed {

        private enumSpeedUnits unitsField;

        private XmlAttribute[] anyAttrField;

        private string textField;

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumSpeedUnits Units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }

        /// <remarks/>
        [XmlTextAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public enum enumSpeedUnits {

        /// <remarks/>
        kph,

        /// <remarks/>
        [XmlEnumAttribute("m/s")]
        ms,

        /// <remarks/>
        mph,

        /// <remarks/>
        fps,
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class DetectorData {

        private string remarkField;

        private DateTime startTimeField;

        private bool startTimeFieldSpecified;

        private string sampleRealTimeField;

        private string occupiedField;

        private Speed speedField;

        private bool alarmSummaryField;

        private bool alarmSummaryFieldSpecified;

        private string[] alarmDescriptionField;

        private DetectorMeasurement[] detectorMeasurementField;

        private XmlElement[] anyField;

        private XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        public DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool StartTimeSpecified {
            get {
                return this.startTimeFieldSpecified;
            }
            set {
                this.startTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(DataType = "duration")]
        public string SampleRealTime {
            get {
                return this.sampleRealTimeField;
            }
            set {
                this.sampleRealTimeField = value;
            }
        }

        /// <remarks/>
        public string Occupied {
            get {
                return this.occupiedField;
            }
            set {
                this.occupiedField = value;
            }
        }

        /// <remarks/>
        public Speed Speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
            }
        }

        /// <remarks/>
        public bool AlarmSummary {
            get {
                return this.alarmSummaryField;
            }
            set {
                this.alarmSummaryField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool AlarmSummarySpecified {
            get {
                return this.alarmSummaryFieldSpecified;
            }
            set {
                this.alarmSummaryFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("AlarmDescription")]
        public string[] AlarmDescription {
            get {
                return this.alarmDescriptionField;
            }
            set {
                this.alarmDescriptionField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("DetectorMeasurement")]
        public DetectorMeasurement[] DetectorMeasurement {
            get {
                return this.detectorMeasurementField;
            }
            set {
                this.detectorMeasurementField = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class ItemToDetectorDistance {

        private enumDistanceUnits unitsField;

        private XmlAttribute[] anyAttrField;

        private double valueField;

        /// <remarks/>
        [XmlAttributeAttribute()]
        public enumDistanceUnits Units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }

        /// <remarks/>
        [XmlTextAttribute()]
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public enum enumDistanceUnits {

        /// <remarks/>
        mm,

        /// <remarks/>
        cm,

        /// <remarks/>
        m,

        /// <remarks/>
        km,

        /// <remarks/>
        @in,

        /// <remarks/>
        ft,

        /// <remarks/>
        mi,
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class MultimediaData {

        private string dataMIMETypeField;

        private string encodingMIMETypeField;

        private string remarkField;

        private string sequenceNumberField;

        private DateTime timeField;

        private bool timeFieldSpecified;

        private string uRIField;

        private XmlAttribute[] anyAttrField;

        private string valueField;

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string DataMIMEType {
            get {
                return this.dataMIMETypeField;
            }
            set {
                this.dataMIMETypeField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string EncodingMIMEType {
            get {
                return this.encodingMIMETypeField;
            }
            set {
                this.encodingMIMETypeField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "positiveInteger")]
        public string SequenceNumber {
            get {
                return this.sequenceNumberField;
            }
            set {
                this.sequenceNumberField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public DateTime Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool TimeSpecified {
            get {
                return this.timeFieldSpecified;
            }
            set {
                this.timeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "anyURI")]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }

        /// <remarks/>
        [XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class Coordinates {

        private string datumField;

        private DateTime timeField;

        private bool timeFieldSpecified;

        private XmlAttribute[] anyAttrField;

        private string textField;

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "positiveInteger")]
        public string Datum {
            get {
                return this.datumField;
            }
            set {
                this.datumField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public DateTime Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool TimeSpecified {
            get {
                return this.timeFieldSpecified;
            }
            set {
                this.timeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }

        /// <remarks/>
        [XmlTextAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class MeasurementLocation {

        private string remarkField;

        private string measurementLocationNameField;

        private Coordinates[] coordinatesField;

        private XmlElement[] anyField;

        private XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        public string MeasurementLocationName {
            get {
                return this.measurementLocationNameField;
            }
            set {
                this.measurementLocationNameField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("Coordinates")]
        public Coordinates[] Coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                this.coordinatesField = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class ItemQuantity {

        private string unitsField;

        private XmlAttribute[] anyAttrField;

        private string textField;

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }

        /// <remarks/>
        [XmlTextAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242")]
    public partial class MeasuredItemInformation {

        private string remarkField;

        private string itemDescriptionField;

        private ItemQuantity itemQuantityField;

        private MeasurementLocation measurementLocationField;

        private DateTime itemReferenceDateField;

        private bool itemReferenceDateFieldSpecified;

        private MultimediaData multimediaDataField;

        private string measurementGeometryDescriptionField;

        private ItemToDetectorDistance itemToDetectorDistanceField;

        private string measurementOperatorField;

        private XmlElement[] anyField;

        private XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        public string ItemDescription {
            get {
                return this.itemDescriptionField;
            }
            set {
                this.itemDescriptionField = value;
            }
        }

        /// <remarks/>
        public ItemQuantity ItemQuantity {
            get {
                return this.itemQuantityField;
            }
            set {
                this.itemQuantityField = value;
            }
        }

        /// <remarks/>
        public MeasurementLocation MeasurementLocation {
            get {
                return this.measurementLocationField;
            }
            set {
                this.measurementLocationField = value;
            }
        }

        /// <remarks/>
        public DateTime ItemReferenceDate {
            get {
                return this.itemReferenceDateField;
            }
            set {
                this.itemReferenceDateField = value;
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool ItemReferenceDateSpecified {
            get {
                return this.itemReferenceDateFieldSpecified;
            }
            set {
                this.itemReferenceDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public MultimediaData MultimediaData {
            get {
                return this.multimediaDataField;
            }
            set {
                this.multimediaDataField = value;
            }
        }

        /// <remarks/>
        public string MeasurementGeometryDescription {
            get {
                return this.measurementGeometryDescriptionField;
            }
            set {
                this.measurementGeometryDescriptionField = value;
            }
        }

        /// <remarks/>
        public ItemToDetectorDistance ItemToDetectorDistance {
            get {
                return this.itemToDetectorDistanceField;
            }
            set {
                this.itemToDetectorDistanceField = value;
            }
        }

        /// <remarks/>
        public string MeasurementOperator {
            get {
                return this.measurementOperatorField;
            }
            set {
                this.measurementOperatorField = value;
            }
        }

        /// <remarks/>
        [XmlAnyElementAttribute()]
        public XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttributeAttribute()]
        public XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
}
